// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DDDEastAnglia.Controllers
{
    public partial class VoteController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected VoteController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Status()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Status);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RegisterVote()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegisterVote);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoveVote()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveVote);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public VoteController Actions { get { return MVC.Vote; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Vote";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Vote";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Status = "Status";
            public readonly string RegisterVote = "RegisterVote";
            public readonly string RemoveVote = "RemoveVote";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Status = "Status";
            public const string RegisterVote = "RegisterVote";
            public const string RemoveVote = "RemoveVote";
        }


        static readonly ActionParamsClass_Status s_params_Status = new ActionParamsClass_Status();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Status StatusParams { get { return s_params_Status; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Status
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RegisterVote s_params_RegisterVote = new ActionParamsClass_RegisterVote();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RegisterVote RegisterVoteParams { get { return s_params_RegisterVote; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RegisterVote
        {
            public readonly string id = "id";
            public readonly string sessionVoteModel = "sessionVoteModel";
        }
        static readonly ActionParamsClass_RemoveVote s_params_RemoveVote = new ActionParamsClass_RemoveVote();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveVote RemoveVoteParams { get { return s_params_RemoveVote; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveVote
        {
            public readonly string id = "id";
            public readonly string sessionVoteModel = "sessionVoteModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Status = "Status";
            }
            public readonly string Status = "~/Views/Vote/Status.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_VoteController : DDDEastAnglia.Controllers.VoteController
    {
        public T4MVC_VoteController() : base(Dummy.Instance) { }

        partial void StatusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult Status(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Status);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            StatusOverride(callInfo, id);
            return callInfo;
        }

        partial void RegisterVoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DDDEastAnglia.Models.VoteModel sessionVoteModel);

        public override System.Web.Mvc.ActionResult RegisterVote(int id, DDDEastAnglia.Models.VoteModel sessionVoteModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegisterVote);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sessionVoteModel", sessionVoteModel);
            RegisterVoteOverride(callInfo, id, sessionVoteModel);
            return callInfo;
        }

        partial void RemoveVoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, DDDEastAnglia.Models.VoteModel sessionVoteModel);

        public override System.Web.Mvc.ActionResult RemoveVote(int id, DDDEastAnglia.Models.VoteModel sessionVoteModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveVote);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sessionVoteModel", sessionVoteModel);
            RemoveVoteOverride(callInfo, id, sessionVoteModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
