// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DDDEastAnglia.DataAccess.EntityFramework.Migrations
{
    public sealed partial class LinkSessionToConference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkSessionToConference));
        
        string IMigrationMetadata.Id
        {
            get { return "201304170655041_LinkSessionToConference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
