// <auto-generated />
namespace DDDEastAnglia.DataAccess.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CalendarItemTypeEnumWorkAround : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CalendarItemTypeEnumWorkAround));
        
        string IMigrationMetadata.Id
        {
            get { return "201304201405453_CalendarItemTypeEnumWorkAround"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
