// <auto-generated />
namespace DDDEastAnglia.DataAccess.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemoveIsVoteColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveIsVoteColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201304132127266_RemoveIsVoteColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
